# Generated by Django 5.2.17 on 2026-08-14 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_rename_grav_comment_state_created_core_commen_content_b01c83_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('at_risk', 'At risk'), ('achieved', 'Achieved'), ('paused', 'Paused')], db_index=True, default='planned', max_length=16)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('metric_name', models.CharField(blank=True, max_length=120)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'ordering': ['target_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StrategyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('kind', models.CharField(choices=[('vision', 'Vision'), ('roadmap', 'Roadmap'), ('audience', 'Audience'), ('content', 'Content thesis'), ('principles', 'Principles'), ('revenue', 'Revenue model'), ('goals', 'Goals / OKRs'), ('other', 'Other')], db_index=True, default='other', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['kind', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('kind', models.CharField(choices=[('content', 'Content'), ('product', 'Product'), ('research', 'Research'), ('campaign', 'Campaign'), ('operations', 'Operations'), ('partnership', 'Partnership')], db_index=True, default='content', max_length=24)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('blocked', 'Blocked'), ('done', 'Done'), ('archived', 'Archived')], db_index=True, default='planned', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='hq.objective')),
            ],
            options={
                'ordering': ['status', 'due_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done')], default='open', max_length=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='hq.project')),
            ],
            options={
                'ordering': ['due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContentProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('working_title', models.CharField(max_length=240)),
                ('central_question', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('idea', 'Idea'), ('topic_score', 'Topic score'), ('brief', 'Brief'), ('evidence', 'Evidence map'), ('script', 'Script'), ('scientific_review', 'Scientific review'), ('production', 'Production'), ('companion', 'Companion page'), ('distribution', 'Distribution'), ('postmortem', 'Post-mortem'), ('done', 'Done')], db_index=True, default='idea', max_length=32)),
                ('topic_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('brief', models.TextField(blank=True)),
                ('script', models.TextField(blank=True)),
                ('scientific_notes', models.TextField(blank=True)),
                ('distribution_notes', models.TextField(blank=True)),
                ('postmortem', models.TextField(blank=True)),
                ('planned_publish_at', models.DateTimeField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('public_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hq_productions', to='core.contentitem')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_production', to='hq.project')),
            ],
            options={
                'ordering': ['planned_publish_at', 'working_title'],
            },
        ),
        migrations.AddField(
            model_name='objective',
            name='strategy_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='hq.strategydocument'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('role_label', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('paused', 'Paused')], db_index=True, default='active', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hq_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__email'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('todo', 'To do'), ('in_progress', 'In progress'), ('review', 'Review'), ('blocked', 'Blocked'), ('done', 'Done')], db_index=True, default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=16)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('estimate_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependents', to='hq.task')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='hq.milestone')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='hq.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hq.project')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='hq.teammember')),
            ],
            options={
                'ordering': ['sort_order', 'due_at', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='strategydocument',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_owned', to='hq.teammember'),
        ),
        migrations.AddField(
            model_name='strategydocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_updated', to='hq.teammember'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_owned', to='hq.teammember'),
        ),
        migrations.AddField(
            model_name='objective',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectives', to='hq.teammember'),
        ),
        migrations.CreateModel(
            name='EvidenceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('kind', models.CharField(choices=[('paper', 'Paper'), ('dataset', 'Dataset'), ('book', 'Book'), ('article', 'Article / report'), ('interview', 'Interview'), ('video', 'Video'), ('other', 'Other')], db_index=True, default='paper', max_length=16)),
                ('url', models.URLField(blank=True)),
                ('doi', models.CharField(blank=True, max_length=180)),
                ('authors', models.CharField(blank=True, max_length=400)),
                ('publisher', models.CharField(blank=True, max_length=220)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources_added', to='hq.teammember')),
            ],
            options={
                'ordering': ['-published_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement', models.TextField()),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='hq.contentproduction')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_owned', to='hq.teammember')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('asset_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('design', 'Design file'), ('document', 'Document'), ('dataset', 'Dataset'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('provider', models.CharField(choices=[('youtube', 'YouTube'), ('google_drive', 'Google Drive'), ('frame_io', 'Frame.io'), ('vimeo', 'Vimeo'), ('cloudflare_r2', 'Cloudflare R2'), ('s3', 'S3 compatible'), ('external', 'External URL')], db_index=True, default='external', max_length=24)),
                ('url', models.URLField(max_length=1200)),
                ('external_id', models.CharField(blank=True, max_length=240)),
                ('version', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('working', 'Working'), ('review', 'Review'), ('approved', 'Approved'), ('final', 'Final'), ('archived', 'Archived')], db_index=True, default='working', max_length=16)),
                ('size_bytes', models.BigIntegerField(blank=True, help_text='Metadata only; binary is stored externally.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='hq.contentproduction')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='hq.project')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_added', to='hq.teammember')),
            ],
            options={
                'ordering': ['-updated_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ClaimEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stance', models.CharField(choices=[('supports', 'Supports'), ('challenges', 'Challenges'), ('context', 'Context')], default='supports', max_length=16)),
                ('locator', models.CharField(blank=True, help_text='Page, figure, timestamp, section, etc.', max_length=240)),
                ('note', models.TextField(blank=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='hq.claim')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_links', to='hq.evidencesource')),
            ],
            options={
                'ordering': ['claim_id', 'source_id'],
                'constraints': [models.UniqueConstraint(fields=('claim', 'source', 'stance'), name='hq_unique_claim_source_stance')],
            },
        ),
        migrations.CreateModel(
            name='SectionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('dashboard', 'Dashboard'), ('strategy', 'Strategy'), ('projects', 'Projects & tasks'), ('content', 'Content Studio'), ('research', 'Research & evidence'), ('assets', 'Assets'), ('team', 'Team & permissions'), ('community', 'Community Ops'), ('analytics', 'Analytics & KPI')], max_length=24)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'No access'), (10, 'View'), (20, 'Comment'), (30, 'Edit'), (40, 'Manage')], default=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_access', to='hq.teammember')),
            ],
            options={
                'ordering': ['member_id', 'section'],
                'constraints': [models.UniqueConstraint(fields=('member', 'section'), name='hq_unique_member_section')],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('can_manage_tasks', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hq.project')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='hq.teammember')),
            ],
            options={
                'ordering': ['project_id', 'member_id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'member'), name='hq_unique_project_member')],
            },
        ),
    ]
