# Generated for Gravitas Operating Workspace.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_nextcloudidentity_organization_researchproject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('content', 'Media & Content'), ('research', 'Scientific Research'), ('commercial', 'Commercial Scientific Projects'), ('technology', 'Technology & Infrastructure'), ('operations', 'Operations / Management')], max_length=24)),
                ('name', models.CharField(max_length=180)),
                ('flow', models.JSONField(blank=True, default=list)),
                ('cadence', models.JSONField(blank=True, default=list)),
                ('kpis', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gravitas_processes_owned', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_processes', to='core.workspace')),
            ],
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('quarter', models.CharField(blank=True, max_length=32)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('health', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('blocked', 'Blocked'), ('done', 'Done'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gravitas_objectives_owned', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_objectives', to='core.workspace')),
            ],
            options={'ordering': ['-updated_at']},
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('metric_name', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('baseline_value', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('confidence', models.PositiveSmallIntegerField(default=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('health', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('blocked', 'Blocked'), ('done', 'Done'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='core.strategicobjective')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gravitas_key_results_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['objective_id', 'id']},
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('p0', 'P0 · Critical'), ('p1', 'P1 · High'), ('p2', 'P2 · Normal'), ('p3', 'P3 · Low')], default='p2', max_length=8)),
                ('health', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('blocked', 'Blocked'), ('done', 'Done'), ('archived', 'Archived')], default='active', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='core.keyresult')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gravitas_initiatives_owned', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiatives', to='core.operatingprocess')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='core.workspace')),
            ],
            options={'ordering': ['priority', '-updated_at']},
        ),
        migrations.CreateModel(
            name='OperatingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('ad_hoc', 'Ad hoc')], max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('blocked', 'Blocked'), ('done', 'Done'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gravitas_cycles_owned', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='core.operatingprocess')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_cycles', to='core.workspace')),
            ],
            options={'ordering': ['-start_date']},
        ),
        migrations.CreateModel(
            name='OperatingMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('weekly_gravitas', 'Gravitas Weekly'), ('content_editorial', 'Content Editorial'), ('active_project_review', 'Active Project Review'), ('scientific_review', 'Scientific Review'), ('tech_sprint', 'Tech Sprint Planning / Review'), ('monthly_operating_review', 'Monthly Operating Review'), ('okr_planning', 'Strategy & OKR Planning'), ('okr_review', 'OKR Review & Retrospective'), ('client_project_review', 'Client / Project Review')], max_length=36)),
                ('title', models.CharField(max_length=220)),
                ('scheduled_for', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('decisions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('blocked', 'Blocked'), ('done', 'Done'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gravitas_meetings_owned', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='core.operatingprocess')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_meetings', to='core.workspace')),
            ],
            options={'ordering': ['scheduled_for']},
        ),
        migrations.CreateModel(
            name='OperatingMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('definition_of_done', models.TextField(blank=True)),
                ('health', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('blocked', 'Blocked'), ('done', 'Done'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='core.operatingcycle')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.initiative')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gravitas_milestones_owned', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_milestones', to='core.researchproject')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_milestones', to='core.workspace')),
            ],
            options={'ordering': ['due_date', 'id']},
        ),
        migrations.CreateModel(
            name='OperatingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('p0', 'P0 · Critical'), ('p1', 'P1 · High'), ('p2', 'P2 · Normal'), ('p3', 'P3 · Low')], default='p2', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('blocked', 'Blocked'), ('done', 'Done'), ('archived', 'Archived')], default='active', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('definition_of_done', models.TextField()),
                ('blocked_reason', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.operatingcycle')),
                ('dependency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependants', to='core.operatingtask')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.initiative')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='core.operatingmeeting')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.operatingmilestone')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gravitas_tasks_owned', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_tasks', to='core.researchproject')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_tasks', to='core.workspace')),
            ],
            options={'ordering': ['priority', 'due_date', '-updated_at']},
        ),
        migrations.AddConstraint(
            model_name='operatingprocess',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='unique_operating_process_key'),
        ),
        migrations.AddIndex(
            model_name='operatingtask',
            index=models.Index(fields=['workspace', 'status', 'priority'], name='grav_task_status_priority'),
        ),
        migrations.AddIndex(
            model_name='operatingtask',
            index=models.Index(fields=['workspace', 'owner', 'status'], name='grav_task_owner_status'),
        ),
    ]
