import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0006_operating_controls'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('personal', 'Personal'), ('core', 'Core operations'), ('research', 'Scientific research')], db_index=True, default='personal', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('nextcloud_root', models.CharField(default='Gravitas', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_profile', to='core.workspace')),
            ],
            options={'ordering': ['purpose', 'workspace_id']},
        ),
        migrations.CreateModel(
            name='ResearcherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=240)),
                ('bio', models.TextField(blank=True)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('institution', models.CharField(blank=True, max_length=240)),
                ('orcid', models.CharField(blank=True, max_length=40)),
                ('google_scholar_url', models.URLField(blank=True, max_length=1000)),
                ('github_url', models.URLField(blank=True, max_length=1000)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('availability', models.CharField(blank=True, max_length=120)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gravitas_researcher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['user_id']},
        ),
        migrations.CreateModel(
            name='ResearchProjectProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('internal', 'Internal research'), ('client', 'Client / revenue research'), ('community', 'Community research')], db_index=True, default='internal', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('invite', 'Invite only'), ('community', 'Community'), ('public', 'Public')], db_index=True, default='private', max_length=20)),
                ('status', models.CharField(choices=[('intake', 'Intake'), ('active', 'Active'), ('review', 'Review'), ('delivered', 'Delivered'), ('on_hold', 'On hold'), ('closed', 'Closed')], db_index=True, default='intake', max_length=20)),
                ('research_question', models.TextField(blank=True)),
                ('client_name', models.CharField(blank=True, max_length=220)),
                ('requester_name', models.CharField(blank=True, max_length=220)),
                ('requester_email', models.EmailField(blank=True, max_length=254)),
                ('confidentiality', models.CharField(choices=[('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted data room'), ('public', 'Public')], default='internal', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('compensation_text', models.CharField(blank=True, max_length=240)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('application_open', models.BooleanField(default=False)),
                ('public_slug', models.SlugField(blank=True, max_length=220, null=True, unique=True)),
                ('nextcloud_root', models.CharField(blank=True, max_length=700)),
                ('secure_data_room', models.BooleanField(default=False)),
                ('allow_public_links', models.BooleanField(default=False)),
                ('allow_downloads', models.BooleanField(default=True)),
                ('external_access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_profile', to='core.researchproject')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [
                    models.Index(fields=['category', 'status'], name='grav_project_category_status'),
                    models.Index(fields=['visibility', 'application_open'], name='grav_project_public_open'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ContentWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('kind', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('reel', 'Short / Reel'), ('podcast', 'Podcast'), ('design', 'Design'), ('other', 'Other')], db_index=True, default='video', max_length=20)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('selected', 'Selected'), ('research', 'Research'), ('brief', 'Brief'), ('script', 'Script'), ('scientific_review', 'Scientific review'), ('production', 'Production'), ('edit', 'Edit'), ('qa', 'QA'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='idea', max_length=24)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('published_url', models.URLField(blank=True, max_length=1000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gravitas_content_work_created', to=settings.AUTH_USER_MODEL)),
                ('linked_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_work_items', to='core.contentitem')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gravitas_content_work_owned', to=settings.AUTH_USER_MODEL)),
                ('research_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_work_items', to='core.researchproject')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_work_items', to='core.workspace')),
            ],
            options={
                'ordering': ['status', 'due_date', '-updated_at'],
                'indexes': [models.Index(fields=['workspace', 'status', 'kind'], name='grav_content_pipeline')],
            },
        ),
        migrations.CreateModel(
            name='ResearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('brief', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('in_progress', 'In progress'), ('review', 'Review'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('priority', models.CharField(default='p2', max_length=8)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('output_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gravitas_research_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('content_work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_requests', to='core.contentworkitem')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_requests', to='core.researchproject')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gravitas_research_requests_created', to=settings.AUTH_USER_MODEL)),
                ('source_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_requests', to='core.contentitem')),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_requests', to='core.operatingtask')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_requests', to='core.workspace')),
            ],
            options={
                'ordering': ['priority', 'due_date', '-updated_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='grav_research_request_state')],
            },
        ),
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=220)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('profile_url', models.URLField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gravitas_project_applications', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.researchproject')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=Q(('applicant_user__isnull', False)), fields=('project', 'applicant_user'), name='unique_gravitas_user_application')],
            },
        ),
        migrations.CreateModel(
            name='ProjectDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('delivered', 'Delivered')], default='draft', max_length=20)),
                ('client_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gravitas_deliverables_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='core.researchproject')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverables', to='core.knowledgeresource')),
            ],
            options={'ordering': ['status', '-updated_at']},
        ),
        migrations.CreateModel(
            name='MindMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gravitas_mind_maps_owned', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mind_maps', to='core.researchproject')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mind_maps', to='core.workspace')),
            ],
            options={'ordering': ['-updated_at']},
        ),
        migrations.CreateModel(
            name='MindMapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=240)),
                ('body', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('concept', 'Concept'), ('question', 'Question'), ('hypothesis', 'Hypothesis'), ('note', 'Note'), ('paper', 'Paper'), ('dataset', 'Dataset'), ('task', 'Task'), ('other', 'Other')], default='concept', max_length=20)),
                ('linked_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('mind_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.mindmap')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('mind_map', 'key'), name='unique_gravitas_mindmap_node_key')],
            },
        ),
        migrations.CreateModel(
            name='MindMapEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(default='related', max_length=60)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mind_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='core.mindmap')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='core.mindmapnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='core.mindmapnode')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [
                    models.UniqueConstraint(fields=('source', 'target', 'relation'), name='unique_gravitas_mindmap_edge'),
                    models.CheckConstraint(condition=~Q(('source', models.F('target'))), name='no_gravitas_mindmap_self_edge'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ObjectPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('workspace', 'Workspace'), ('project', 'Project'), ('specific', 'Specific people'), ('link', 'Anyone with link'), ('public', 'Public')], db_index=True, default='workspace', max_length=20)),
                ('allow_download', models.BooleanField(default=True)),
                ('allow_reshare', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gravitas_object_policies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_gravitas_object_policy')],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='grav_policy_object')],
            },
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('role', models.CharField(choices=[('view', 'View'), ('comment', 'Comment'), ('edit', 'Edit'), ('manage', 'Manage')], default='view', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gravitas_access_grants_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gravitas_access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'user'), name='unique_gravitas_object_user_grant')],
                'indexes': [models.Index(fields=['user', 'content_type', 'object_id'], name='grav_access_user_object')],
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('view', 'View'), ('comment', 'Comment'), ('edit', 'Edit'), ('manage', 'Manage')], default='view', max_length=16)),
                ('allow_download', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gravitas_share_links_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'active'], name='grav_share_object_active')],
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gravitas_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='EntityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveBigIntegerField()),
                ('target_object_id', models.PositiveBigIntegerField()),
                ('relation', models.CharField(default='related', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gravitas_entity_links_created', to=settings.AUTH_USER_MODEL)),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('source_content_type', 'source_object_id', 'target_content_type', 'target_object_id', 'relation'), name='unique_gravitas_entity_link')],
                'indexes': [
                    models.Index(fields=['source_content_type', 'source_object_id'], name='grav_entity_source'),
                    models.Index(fields=['target_content_type', 'target_object_id'], name='grav_entity_target'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ProjectAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=120)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gravitas_project_audit_events', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.researchproject')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='grav_project_audit_recent')],
            },
        ),
    ]
