# Generated by Django 5.2.18 on 2026-10-07 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_backfill_research_project_structure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ready', 'Ready'), ('waiting', 'Waiting on owner'), ('needs_review', 'Needs review'), ('retest', 'Acceptance retest'), ('blocked', 'Blocked'), ('done', 'Done'), ('archived', 'Archived')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='keyresult',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ready', 'Ready'), ('waiting', 'Waiting on owner'), ('needs_review', 'Needs review'), ('retest', 'Acceptance retest'), ('blocked', 'Blocked'), ('done', 'Done'), ('archived', 'Archived')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='operatingcycle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ready', 'Ready'), ('waiting', 'Waiting on owner'), ('needs_review', 'Needs review'), ('retest', 'Acceptance retest'), ('blocked', 'Blocked'), ('done', 'Done'), ('archived', 'Archived')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='operatingmeeting',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ready', 'Ready'), ('waiting', 'Waiting on owner'), ('needs_review', 'Needs review'), ('retest', 'Acceptance retest'), ('blocked', 'Blocked'), ('done', 'Done'), ('archived', 'Archived')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='operatingmilestone',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ready', 'Ready'), ('waiting', 'Waiting on owner'), ('needs_review', 'Needs review'), ('retest', 'Acceptance retest'), ('blocked', 'Blocked'), ('done', 'Done'), ('archived', 'Archived')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='operatingrisk',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ready', 'Ready'), ('waiting', 'Waiting on owner'), ('needs_review', 'Needs review'), ('retest', 'Acceptance retest'), ('blocked', 'Blocked'), ('done', 'Done'), ('archived', 'Archived')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='operatingtask',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ready', 'Ready'), ('waiting', 'Waiting on owner'), ('needs_review', 'Needs review'), ('retest', 'Acceptance retest'), ('blocked', 'Blocked'), ('done', 'Done'), ('archived', 'Archived')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='operatingworkpackage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ready', 'Ready'), ('waiting', 'Waiting on owner'), ('needs_review', 'Needs review'), ('retest', 'Acceptance retest'), ('blocked', 'Blocked'), ('done', 'Done'), ('archived', 'Archived')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='strategicobjective',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ready', 'Ready'), ('waiting', 'Waiting on owner'), ('needs_review', 'Needs review'), ('retest', 'Acceptance retest'), ('blocked', 'Blocked'), ('done', 'Done'), ('archived', 'Archived')], default='active', max_length=16),
        ),
        migrations.CreateModel(
            name='CanonicalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('etag', models.CharField(blank=True, max_length=240)),
                ('file_id', models.CharField(blank=True, max_length=120)),
                ('base_content', models.TextField(blank=True)),
                ('deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_files', to='core.researchproject')),
            ],
        ),
        migrations.CreateModel(
            name='CanonicalFileRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etag', models.CharField(blank=True, max_length=240)),
                ('content', models.TextField()),
                ('source', models.CharField(default='gravitas', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.canonicalfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('migration_backup_path', models.CharField(blank=True, max_length=1000)),
                ('last_error', models.TextField(blank=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_storage', to='core.researchproject')),
            ],
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyWorkReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('source', models.CharField(default='platform', max_length=32)),
                ('source_key', models.CharField(max_length=180)),
                ('original_text', models.TextField()),
                ('interpretation', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Needs confirmation'), ('confirmed', 'Confirmed by user'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='core.dailyworkreport')),
                ('tasks', models.ManyToManyField(blank=True, related_name='daily_work_reports', to='core.operatingtask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_work_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='canonicalfile',
            constraint=models.UniqueConstraint(fields=('project', 'path'), name='unique_canonical_project_path'),
        ),
        migrations.AddConstraint(
            model_name='dailycheckin',
            constraint=models.UniqueConstraint(fields=('user', 'report_date'), name='unique_daily_checkin'),
        ),
        migrations.AddConstraint(
            model_name='dailyworkreport',
            constraint=models.UniqueConstraint(fields=('user', 'source', 'source_key'), name='unique_confirmed_work_input'),
        ),
    ]
