# Generated by Django 5.2.18 on 2026-10-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_canonical_files_and_confirmed_daily_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkreport',
            name='proposal_history',
            field=models.JSONField(default=list),
        ),
    ]
