# Generated by Django 5.2.18 on 2026-10-07 20:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_work_report_proposal_provenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalWriteCommit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
